### ISSUE TITLE
Organize assets

### ISSUE THREAD

**Issue by Nanomotion** [card100/torminal#12]
Maybe create a `/assets` directory to organize things like CSS, JS, images, or other resources? It would help clean up a bit.

**Comment by Torotv** [comment]
Done.

**Comment by Nanomotion** [comment]
For whatever reason, that kid closed this issue.

**Comment by GreenBayRules** [comment]
what the hell is  redmangos pros problem! How the hell can he close issues anyways

**Comment by Nanomotion** [comment]
I have no idea

**Comment by card100** [comment]
https://github.com/card100/torminal/pull/37
Done
