### ISSUE TITLE
Clear 

### ISSUE THREAD

**Issue by Torotv** [card100/torminal#18]
Maybe, When We Write Clear, Or Someone else, It Should Clear Only The Commands or Git Commands they Did, Not Everything like time date and time zone.

What Do You Think @card100 Or @Nanomotion @csf30816 @Greenbayrules

**Comment by card100** [comment]
I see what your saying and I do agree.  The problem is that it's not the easiest thing to fix.  How about when the clear command has been run it outputs the time without the whole logo staying.

**Comment by Torotv** [comment]
Nice, But The logo V=Can Load Affter Right?
