### ISSUE TITLE
Run command

### ISSUE THREAD

**Issue by csf30816** [card100/torminal#20]
There should be a `run` command that runs the specified JS code. This _could_ be done with evil eval if I am correct :)

**Comment by card100** [comment]
Could there be a run command that starts a supported file and the eval would be a string of JS?

**Comment by card100** [comment]
We would also need sandboxing in the JS

**Comment by Nanomotion** [comment]
`cat` is usually for running files and `eval` is for running JS and math, at least that's what I do

**Comment by card100** [comment]
Ok

**Comment by card100** [comment]
@Nanomotion do you want to work on this?  You will need to make sure that you have a sandboxing system in place.

**Comment by Torotv** [comment]
What Can I Work On?

**Comment by Nanomotion** [comment]
@Torotv You can work on getting hype for the project
@card100 Sounds good

**Comment by Torotv** [comment]
Hype Okay? ( How?)
Can I DO Some Coding Editing You Can Tell Me What To Change.

**Comment by card100** [comment]
We can't get going until the Filesystem API is finished.  Still working on it.

**Comment by csf30816** [comment]
@Nanomotion OK, so evil `eval` command for both JS and Math - got it. Closing this now.

**Comment by card100** [comment]
I'm going to keep this open till I finish the eval running part.

**Comment by csf30816** [comment]
OK

**Comment by card100** [comment]
Closing for right now

**Comment by card100** [comment]
I work on it once an a while

**Comment by GreenBayRules** [comment]
wow
