### ISSUE TITLE
Temporary vs Permanent file system

### ISSUE THREAD

**Issue by card100** [card100/torminal#22]
For now, I'm setting up the filesystem API as temporary but later we can add a feature that you can turn on permanent.  When that time comes, what do you guys think the default setting should be?

For now we're only going to give torminal a 5mb but later we can make a cmd to add more

**Comment by Torotv** [comment]
Okay. Nice Idea.

**Comment by csf30816** [comment]
Sounds good

**Comment by VutonDesign** [comment]
I'm not part of the team but, Nice Idea! 😆
