### ISSUE TITLE
ListCommands

### ISSUE THREAD

**Issue by GreenBayRules** [card100/torminal#27]
Planning on making a command that lists the different commands. What should it be called?

**Comment by redmangospros** [comment]
coomandslist

**Comment by GreenBayRules** [comment]
Any other ideas @card100 @Nanomotion

**Comment by GreenBayRules** [comment]
maybe just commands

**Comment by redmangospros** [comment]
Commando

**Comment by Nanomotion** [comment]
or `help --list`?

**Comment by GreenBayRules** [comment]
hmm help sounds good.

**Comment by GreenBayRules** [comment]
nvm apparently has already been added

**Comment by card100** [comment]
It has?

**Comment by GreenBayRules** [comment]
yep "help"
