### ISSUE TITLE
No Commands Wok.

### ISSUE THREAD

**Issue by Torotv** [card100/torminal#3]
Not Commands Are Working.
Here IS An Attched Srceenshot

![help](https://user-images.githubusercontent.com/21000033/30943129-0070b490-a3bd-11e7-816f-15acc71505e2.png)

**Comment by Torotv** [comment]
Nevermind

**Comment by Torotv** [comment]
'''
Mak

**Comment by card100** [comment]
Is it working now?

Not sure why it's doing that.
