### ISSUE TITLE
Not working on chromeOS

### ISSUE THREAD

**Issue by Narulacodes** [card100/torminal#36]
The Terimnal is not working on chrome os
**My browser / operating system: ChromeOS 10032.86.0, Chrome 63.0.3239.140, Flash 28.0 (release 0)**

**Comment by Nanomotion** [comment]
can you attach a screenshot?

**Comment by Narulacodes** [comment]
Sure

**Comment by card100** [comment]
Yeah, I think I broke it but haven't had time to fix it

**Comment by Nanomotion** [comment]
I get this error `torminal.js:195 Uncaught SyntaxError: missing ) after argument list`, looks like we're just missing a parenthesis somewhere

**Comment by card100** [comment]
I'll see if I have time today to look through my commits

**Comment by Narulacodes** [comment]
K

**Comment by card100** [comment]
Fixed:
https://github.com/card100/torminal/commit/04ad4f3e7a8a210f3dc5f2ccb228c9f943c68b2d

**Comment by GreenBayRules** [comment]
That commit didn't work, but I have fixed it now.
