### ISSUE TITLE
Math operations

### ISSUE THREAD

**Issue by GreenBayRules** [card100/torminal#8]
Should we have calculator commands? Like for example
(30 + 12) * 2
84

**Comment by Nanomotion** [comment]
Maybe we could have an eval command?

**Comment by card100** [comment]
We can have both.

**Comment by Torotv** [comment]
Great. We Can Get It!

**Comment by GreenBayRules** [comment]
I'll add this when I get home. Are we doing the eval command then?

**Comment by csf30816** [comment]
Yes use eval. I made one of these that used eval once worked fine :)

**Comment by Torotv** [comment]
Guys, Maybe Something like this?
'''
<!DOCTYPE html>
<html>
<body>

<p>Click the button to evaluate/execute JavaScript code/expressions.</p>

<button onclick="myFunction()">Try it</button>

<p id="demo"></p>

<script>
function myFunction() {
    var x = 10;
    var y = 20;
    var a = eval("x * y") + "<br>";
    var b = eval("2 + 2") + "<br>";
    var c = eval("x + 17") + "<br>";

    var res = a + b + c;
    document.getElementById("demo").innerHTML = res;
}
</script>

</body>
</html>

**Comment by card100** [comment]
The eval command sounds good

**Comment by GreenBayRules** [comment]
I think it should be eval(2 + 2) not with quotation marks.

**Comment by card100** [comment]
Are quotation marks normal?

**Comment by GreenBayRules** [comment]
no, quotation marks usually denote a string.

**Comment by Torotv** [comment]
Guys, Maybe Something like this?
'''
<!DOCTYPE html>
<html>
<body>

<p>Click the button to evaluate/execute JavaScript code/expressions.</p>

<button onclick="myFunction()">Try it</button>

<p id="demo"></p>

<script>
function myFunction() {
    var x = 10;
    var y = 20;
    var a = eval("x * y") + "<br>";
    var b = eval("2 + 2") + "<br>";
    var c = eval("x + 17") + "<br>";

    var res = a + b + c;
    document.getElementById("demo").innerHTML = res;
}
</script>

</body>
</html>

**Comment by card100** [comment]
If quotation marks aren't normal the we will leave them out

**Comment by Nanomotion** [comment]
That's a demo, why would we need it exactly?

**Comment by Torotv** [comment]
CAN ANYONE NOTICE THIS??
Guys, Maybe Something like this?
'''

Click the button to evaluate/execute JavaScript code/expressions.

Try it

<script> function myFunction() { var x = 10; var y = 20; var a = eval("x * y") + "
"; var b = eval("2 + 2") + "
"; var c = eval("x + 17") + "
"; var res = a + b + c; document.getElementById("demo").innerHTML = res; } </scri

**Comment by Nanomotion** [comment]
Above comment @Torotv

**Comment by Torotv** [comment]
Hey!

**Comment by card100** [comment]
Ok sounds good.

**Comment by csf30816** [comment]
@Torotv Why do you keep closing and reopening issues?

**Comment by csf30816** [comment]
@Nanomotion Why not name the case `calc` or something along those lines?

**Comment by csf30816** [comment]
I added a `break;` and removes unnecessary semicolons. Here is the edited version:

```
case 'calc':
          output( eval(args.join(' ')) );
          break;
```

You can test it out here: http://csf30816.github.io/torminal/ I tested it everything works *except* `10^2` which results in `8` rather than `100`. This may have something to do with `^` having some other meaning in JS

**Comment by Torotv** [comment]
I Have Added It Here. Tell me to remove or fix.

**Comment by card100** [comment]
Problems that still need to be done:

1. Exponents Ex:`6^2`
2. () Ex: `8(8)`

Report any others that you find

**Comment by card100** [comment]
Solution to all of our problems! 
http://mathjs.org/
I am already working on adding it

**Comment by card100** [comment]
#21
