### ISSUE TITLE
What is the beta branch?

### ISSUE THREAD

**Issue by card100** [card100/torminal#9]

**Comment by Torotv** [comment]
A Branch For Beta Changes.

**Comment by card100** [comment]
Ok

**Comment by Nanomotion** [comment]
Why do we need it? We just post releases when we want... Plus gh-pages doesn't work on any branch besides `master` or `gh-pages`

**Comment by GreenBayRules** [comment]
yeah lets just use the master branch.

**Comment by Torotv** [comment]
Okay. I made that branch for meh.
